Resources:
  TestTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TestTable
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST