name: Deploy to AWS CloudFormation - dev

on: 
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from dev branch
        uses: actions/checkout@v2

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
      #     aws-region: us-east-2
      - run: npm ci
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          # name: node-api-main
          # template: serverless.yml
          # parameters:
          #   stage: ${{ github.event.inputs.stage }}